2022-04-18 16:25:45,573 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 16:25:53,713 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 16:37:43,943 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 16:37:55,475 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 16:38:02,203 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 16:38:17,832 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 16:38:21,514 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 16:40:17,502 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 16:40:31,805 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 16:40:42,467 ERROR: Exception on / [GET] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "Z:\_\microblog\app\main\routes.py", line 59, in index
    .order_by(ProgrammeList.time.asc()).all()
  File "Z:\_\microblog\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2759, in all
    return self._iter().all()
  File "Z:\_\microblog\venv\lib\site-packages\sqlalchemy\engine\result.py", line 1067, in all
    return self._allrows()
  File "Z:\_\microblog\venv\lib\site-packages\sqlalchemy\engine\result.py", line 400, in _allrows
    rows = self._fetchall_impl()
  File "Z:\_\microblog\venv\lib\site-packages\sqlalchemy\engine\result.py", line 1686, in _fetchall_impl
    return list(self.iterator)
  File "Z:\_\microblog\venv\lib\site-packages\sqlalchemy\orm\loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "Z:\_\microblog\venv\lib\site-packages\sqlalchemy\engine\result.py", line 392, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "Z:\_\microblog\venv\lib\site-packages\sqlalchemy\engine\result.py", line 392, in <listcomp>
    return [make_row(row) for row in rows]
ValueError: Couldn't parse datetime string: '16:00'
2022-04-18 17:11:01,446 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 17:42:45,662 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 17:43:01,210 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 17:49:25,126 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 17:59:24,599 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 17:59:26,183 ERROR: Exception on /index [GET] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "Z:\_\microblog\app\main\routes.py", line 87, in index
    return render_template('index.html', title=_('Home'),
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "Z:\_\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "Z:\_\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'html'
    {% block body -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block content -%}
  File "Z:\_\microblog\app\templates\base.html", line 251, in block 'content'
    {% block current_app_content %}{% endblock %}
  File "Z:\_\microblog\app\templates\index.html", line 322, in block 'current_app_content'
    {{ moment(item.date).local().fromNow() }}
TypeError: 'bool' object is not callable
2022-04-18 17:59:37,536 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 18:01:18,719 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 18:04:38,835 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 18:04:39,254 ERROR: Exception on /index [GET] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "Z:\_\microblog\app\main\routes.py", line 87, in index
    return render_template('index.html', title=_('Home'),
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "Z:\_\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "Z:\_\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'html'
    {% block body -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block content -%}
  File "Z:\_\microblog\app\templates\base.html", line 251, in block 'content'
    {% block current_app_content %}{% endblock %}
  File "Z:\_\microblog\app\templates\index.html", line 322, in block 'current_app_content'
    {{ moment(item.date).fromDate() }}
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'flask_moment.moment object' has no attribute 'fromDate'
2022-04-18 18:04:52,169 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 18:23:49,662 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:138]
2022-04-18 21:12:48,836 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:158]
2022-04-18 21:12:53,409 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:158]
2022-04-18 22:46:50,204 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:179]
2022-04-18 22:46:53,888 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:179]
2022-04-19 08:41:39,088 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:178]
2022-04-19 08:42:57,247 ERROR: Exception on /forumpost/index [GET] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'main.forumpost' did not return a valid response. The function either returned None or ended without a return statement.
