2022-04-15 05:02:27,606 ERROR: Exception on /user/Jerry [GET] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "Z:\_\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "Z:\_\microblog\app\main\routes.py", line 97, in user
    return render_template('user.html', user=user, form=form, posts=posts.items,
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "Z:\_\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "Z:\_\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'html'
    {% block body -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block content -%}
  File "Z:\_\microblog\app\templates\base.html", line 237, in block 'content'
    {% block current_app_content %}{% endblock %}
  File "Z:\_\microblog\app\templates\user.html", line 26, in block 'current_app_content'
    {{ wtf.quick_form(form) }}
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2022-04-15 05:02:52,466 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:90]
2022-04-15 05:04:04,389 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:90]
2022-04-15 05:04:12,347 ERROR: Exception on /user/Jerry [POST] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "Z:\_\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "Z:\_\microblog\app\main\routes.py", line 96, in user
    return redirect(url_for('main.user'))
  File "Z:\_\microblog\venv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "Z:\_\microblog\venv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "Z:\_\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.user'. Did you forget to specify values ['username']?
2022-04-15 05:04:37,812 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:90]
2022-04-15 05:19:38,536 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:90]
2022-04-15 05:24:12,674 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:90]
2022-04-15 05:24:20,869 ERROR: Exception on /user/Guest [GET] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "Z:\_\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "Z:\_\microblog\app\main\routes.py", line 101, in user
    return render_template('user.html', user=user, form=form, posts=posts.items,
UnboundLocalError: local variable 'form' referenced before assignment
2022-04-15 05:24:38,720 ERROR: Exception on /user/Guest [GET] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "Z:\_\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "Z:\_\microblog\app\main\routes.py", line 101, in user
    return render_template('user.html', user=user, form=form, posts=posts.items,
UnboundLocalError: local variable 'form' referenced before assignment
2022-04-15 05:29:03,961 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:90]
2022-04-15 05:30:17,140 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:90]
2022-04-15 05:47:04,594 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:90]
2022-04-15 05:47:08,818 ERROR: Exception on /user/Jerry [GET] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "Z:\_\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "Z:\_\microblog\app\main\routes.py", line 84, in user
    posts = (user.posts.order_by(Post.timestamp.desc())
TypeError: unsupported operand type(s) for +: 'BaseQuery' and 'BaseQuery'
2022-04-15 05:48:32,717 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:90]
2022-04-15 05:52:35,350 INFO: Microblog startup [in Z:\_\microblog\app\__init__.py:90]
